config/routes.rb
Maishu::Application.routes.draw do
  resources :orders do
    get 'search', :on => :collection
    post 'search', :on => :collection
    get 'all', :on => :collection
    post 'all', :on => :collection
  end

  resources :line_items


  resources :carts


  devise_for :users

  get "store/index"

  resources :books do
    post 'import', :on => :collection
    get 'search', :on => :collection
    post 'search', :on => :collection
    get :who_bought, on: :member
  end

  root :to => 'store#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	has_many :line_items, dependent: :destroy
	attr_accessible :address, :email, :name, :telephone, :status

	validates :address, :telephone,  presence: true

	STATUS = [ "", "等待发货中", "发货中", "购书已完成" ]

	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_user
  # GET /orders
  # GET /orders.json
  def all
    @orders = Order.all
  end

  def search
    if params[:query]
      query = params[:query].strip
      @orders = Order.where("id like ?", query)
    else
      @orders = current_user.orders
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
    # render layout: nil
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])
    @line_items = @order.line_items

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @cart = current_cart
    if @cart.line_items.empty?
      redirect_to book_url, notice: "您的购物车为空"
      return
    end

    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    flash[:notice] = []
    @order = Order.new(params[:order])
    @order.add_line_items_from_cart(current_cart)
    @order.user_id = current_user.id
    @order.address = current_user.address
    @order.line_items.each do |item|
      book = Book.find(item.book_id)
      if (book.left - item.quantity) < 0
        flash[:notice] << "#{ book.name }库存不足"
      end
    end
    
    if flash[:notice].present?
      redirect_to cart_path(session[:cart_id])
      return true
    end
    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        @order.line_items.each do |item|
          Book.reduce(item.book_id, item.quantity)
        end
        format.html { redirect_to books_path, notice: '感谢您的订单!' }
        format.json { render json: @order, status: :created,location: @order }
      else
        @cart = current_cart
        format.html { render action: "new" }
        format.json { render json: @order.errors,status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to search_orders_url }
      format.json { head :no_content }
    end
    # redirect_to all_orders_path , notice: "订单已删除"
  end

  private
  def get_user
    @user = current_user
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="center">
  <blockquote class="center_major_bq">
    <p>确认收货人信息</p>
  </blockquote>
  <%= form_for(@order, html:{ :class => "form-horizontal" }) do |f| %>
    <% if @order.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

        <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="control-group">
      <%= f.label :name, "姓名", :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :name, :value => @user.name || "" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :address, "地址", :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :address, :value => @user.address || "" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :telephone, "电话", :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :telephone, :value => @user.telephone || "" %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <%= f.submit "提交订单", class:"btn" %>
      </div>
    </div>

    <div class="actions">
    </div>
  <% end %>
</div>

app/views/orders/all.html.erb
<% if current_user.has_role? :admin %>
<div class="center">
  <blockquote class="center_major_bq">
    <p>查询订单</p>
  </blockquote>

  <%= form_tag "/orders/search" do %>
    <div class="input-append">
      <%= text_field_tag :query, nil, :placeholder => "输入订单号" %>
      <%= submit_tag "搜索", class:"btn" %>
    </div>
  <% end %>


  <blockquote class="center_major_bq">
    <p>订单详情</p>
  </blockquote>
  <table class="table table-bordered table-striped">
    <tr>
      <th>订单编号</th>
      <th>订单状态</th>
      <th>收货人姓名</th>
      <th>学校</th>
      <th>地址</th>
      <th>手机</th>
      <th>总价</th>
      <th>下单时间</th>
      <th>操作</th>
    </tr>

  <% @orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
      <td><%= order.status %></td>
      <td><%= order.name %></td>
      <td></td>
      <td><%= order.address %></td>
      <td><%= order.telephone %></td>
      <td><%= order.total_price %></td>
      <td><%= order.created_at %></td>
      <td>
        <%= link_to '删除', order, method: :delete, data: { confirm: '确定？' }, class:"btn" %>
        <%= link_to '查看', order_path(order), class:"btn" %>
      </td>
    </tr>
  <% end %>
  </table>
</div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', search_orders_path %>

app/views/orders/new.html.erb
<%= render 'form' %>

app/views/orders/search.html.erb
<div class="center">
  <blockquote class="center_major_bq">
    <p>查询订单</p>
  </blockquote>

  <%= form_tag "/orders/search" do %>
    <div class="input-append">
      <%= text_field_tag :query, nil, :placeholder => "输入订单号" %>
      <%= submit_tag "搜索", class:"btn" %>
    </div>
  <% end %>


  <blockquote class="center_major_bq">
    <p>订单详情</p>
  </blockquote>
  <table class="table table-bordered table-striped">
    <tr>
      <th>订单编号</th>
      <th>订单状态</th>
      <th>收货人姓名</th>
      <th>学校</th>
      <th>地址</th>
      <th>手机</th>
      <th>总价</th>
      <th>下单时间</th>
      <th>操作</th>
    </tr>

  <% @orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
      <td><%= order.status %></td>
      <td><%= order.name %></td>
      <td><%= order.user.school %></td>
      <td><%= order.address %></td>
      <td><%= order.telephone %></td>
      <td><%= order.total_price %></td>
      <td><%= order.created_at %></td>
      <td>
        <%= link_to '查看', order_path(order), class:"btn btn-default" %>
        <%= link_to '取消订单', order, class:"btn btn-danger", method: :delete, data: { confirm: '真的不想要了吗？' } %>
      </td>


    </tr>
  <% end %>
  </table>
</div>

app/views/orders/show.html.erb
<div class="center">
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
  <blockquote class="center_major_bq">
    <p>订单详情</p>
  </blockquote>
<p>
	<b>收件人:</b>
	<%= @order.name %>
</p>

<p>
	<b>收件地址:</b>
	<%= @order.address %>
</p>

<p>
	<b>手机号码:</b>
	<%= @order.telephone %>
</p>
<table class="table table-bordered table-striped">
  <tr>
  	<th>书籍编号</th>
    <th>书名</th>
    <th>作者</th>
    <th>出版社</th>
    <th style="text-align:right;">数量</th>
    <th style="text-align:right;">价格</th>
  </tr>
	<% @order.line_items.each do |item| %>
    <tr class="total_line">
    	<td><%= item.book.number %></td>
      <td><%= item.book.name %></td>
      <td><%= item.book.author %></td>
      <td><%= item.book.publishing_house %></td>
      <td style="text-align:right;"><%= item.quantity %></td>
      <td class="item_price" style="text-align:right;"><%= item.total_price.to_s + "元" %></td>
    </tr>
  <% end %>
  <tr class="total_line">
    <td colspan="1">总价</td>
    <td colspan="5" class="total_cell" style="text-align:right;">
      <%= @order.total_price.to_s + "元" %>
    </td> 
	</tr>
</table>
</div>
<br />

<%= link_to "返回", all_orders_path, class:"btn" %>