config/routes.rb
Maishu::Application.routes.draw do
  resources :orders do
    get 'search', :on => :collection
    post 'search', :on => :collection
    get 'all', :on => :collection
    post 'all', :on => :collection
  end

  resources :line_items


  resources :carts


  devise_for :users

  get "store/index"

  resources :books do
    post 'import', :on => :collection
    get 'search', :on => :collection
    post 'search', :on => :collection
    get :who_bought, on: :member
  end

  root :to => 'store#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_book(book_id, quantity)
		current_item = line_items.find_by_book_id(book_id)
		if current_item
			current_item.quantity += quantity
		else
			current_item = line_items.build(book_id: book_id)
			current_item.quantity = quantity
		end
		current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :authenticate_user!
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  # def show
  #   begin
  #     @cart = Cart.find(params[:id])
  #   rescue ActiveRecord::RecordNotFound
  #     logger.error "Attempt to access invalid cart #{params[:id]}"
  #     redirect_to books_path, notice: 'Invalid cart'
  #   else
  #     render layout: nil
  #   end
  # end

  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to book_url, notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: '购物车创建成功！' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to books_path, notice: "您的购物车现在为空" }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="cart_title">购物车</div>
<table>
	<%= render(cart.line_items) %>

	<tr class="total_line">
		<td colspan="2">总价</td>
		<td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
	</tr>
</table>

<%= button_to '清空购物车', cart, method: :delete, confirm:"确定清空?" %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/order_index.html.erb
<!DOCTYPE html>
<!-- saved from url=(0053)http://www.1haoshudian.com/index.php?m=index&a=sorder -->
<html lang="zh" slick-uniqueid="3">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
	<title>1号书店</title>
	<%= stylesheet_link_tag "common" %>
	<%= stylesheet_link_tag "yu" %>
	<%= stylesheet_link_tag "bootstrap-2-3" %>
	<%= stylesheet_link_tag "base" %>
	<%= javascript_include_tag "yu" %>
	<body cz-shortcut-listen="true">
		<input type="hidden" id="temp_keyword" value="">
		
		<div class="navbar navbar-fixed-top navbar-inverse">
			<div class="navbar-inner">
				<div class="container">
					<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>
					<a class="brand" href="/">1号书店</a>



					<div class="header_center_right">
						<ul class="nav pull-left">
							<li>
								<%= link_to "书籍", books_path %>
							</li>
							<li>
								<%= link_to "购物车", carts_path %>
							</li>
							<li class="divider-vertical"></li>
						</ul>
						<form class="navbar-search" action="">
							<input type="hidden" name="m" value="index">
							<input type="hidden" name="a" value="books">
							<input type="hidden" name="search" value="y">
							<input class="search-query span3" id="h_search" name="keyword" type="text" placeholder="ISBN、书名、作者、出版社" >
						</form>
						<ul class="nav pull-right">
							<% if user_signed_in? %>
							<li>
								<%= link_to current_user.email, edit_user_registration_path %>
							</li>
							<li>
								<%= link_to "退出", destroy_user_session_path, :method => :delete %>
							</li>
							<% else %>
							<li>
								<%= link_to "注册", new_user_registration_path %>
							</li>
							<li>
								<%= link_to "登录", new_user_session_path %>
							</li>
							<% end %>
						</ul></div>
					</div>
				</div>
			</div><!-- navbar navbar-fixed-top navbar-inverse -->
			<div class="center sorder_center">
				<div style="margin-bottom:32px;">
					<blockquote>
						<p>查询订单</p>
					</blockquote>
					<form class="form-search" method="post">
						<div class="input-append">
							<input class="span2 search-query" id="order_search" type="text" name="keyword" placeholder="订单编号或手机" value="">
							<button class="btn" type="submit">搜</button>
						</div>
					</form>
				</div>
				<div class="center_detail">
					<blockquote>
						<p>订单详情</p>
					</blockquote>
					<table class="table table-bordered table-striped">
						<thead>
							<tr>
								<th>订单编号</th>
								<th>订单状态</th>
								<th>收货人姓名</th>
								<th>学校</th>
								<th>地址</th>
								<th>手机</th>
								<th>总价</th>
								<th>下单时间</th>
								<th>操作</th>
							</tr>
						</thead>
					</table>
				</div>
			</div>
			<div class="cart">
				<div class="cart_content">
					<div class="cart_content_list" id="cart_content_list" onmouseover="$(&#39;#cart_content_list&#39;).show();" onmouseout="$(&#39;#cart_content_list&#39;).hide();">
						<table class="table table-bordered" style="margin:0">
							<thead>
								<tr>
									<th>书名</th>
									<th>单价</th>
									<th>数量</th>
									<th>总价</th>
									<th>删除</th>
								</tr>
							</thead>
							<tbody id="cart_content_list_con">
								<%= @cart.line_items do |item| %>
								<tr>
									<td><%= item.book.name %></td>
									<td><%= number_to_currency(item.total_price) %></td>
									<td>
										<input id="cart_content_list_con_num_629" type="text" style="width:36px;height:16px;margin:0px;" value="1">
										&nbsp; <i class="pointer icon-ok" data-id="629" onclick="my_js.cartChNum(this);"></i>
									</td>
									<td id="cart_content_list_con_allprice_629"><%= number_to_currency(@cart.total_price) %></td>
									<td> <i onclick="my_js.deleteThis(this)" data-id="629" class="icon-trash" style="cursor:pointer"></i>
									</td>
								</tr>
								<% end %>
							</tbody>
						</table>
					</div>
					<div class="cart_content_bar navbar navbar-inverse">
						<ul class="nav">
							<li>
								<a class="pointer" onmouseover="$(&#39;#cart_content_list&#39;).show();" onmouseout="$(&#39;#cart_content_list&#39;).hide();">订单详情</a>
							</li>
							<li class="divider-vertical"></li>
							<li>
								<a id="clr_all" class="pointer pl_6" onclick="my_js.clrAll();">清空</a>
							</li>
						</ul>
						<ul class="nav pull-right">
							<li style="width:220px;text-align:right;">
								<a>
									共
									<span id="cart_content_bar_right_booknum">1</span>
									本书、合计
									<span id="cart_content_bar_right_price">30</span>
									元
								</a>
							</li>
							<li class="divider-vertical"></li>
							<li>
								<a href="http://www.1haoshudian.com/index.php?m=index&a=buy">买单</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="footer">
				<div class="footer_content">关于我们 | 联系我们 | 加入我们</div>
			</div>
			<div id="floatTools" class="float0831">
				<div class="floatL">
					<a id="aFloatTools_Show" class="btnOpen" title="查看在线客服" onclick="javascript:$(&#39;#divFloatToolsView&#39;).animate({width: &#39;show&#39;, opacity: &#39;show&#39;}, &#39;normal&#39;,function(){ $(&#39;#divFloatToolsView&#39;).show();kf_setCookie(&#39;RightFloatShown&#39;, 0, &#39;&#39;, &#39;/&#39;, &#39;www.istudy.com.cn&#39;); });$(&#39;#aFloatTools_Show&#39;).attr(&#39;style&#39;,&#39;display:none&#39;);$(&#39;#aFloatTools_Hide&#39;).attr(&#39;style&#39;,&#39;display:block&#39;);" href="javascript:void(0);">展开</a>
					<a style="display: none" id="aFloatTools_Hide" class="btnCtn" title="关闭在线客服" onclick="javascript:$(&#39;#divFloatToolsView&#39;).animate({width: &#39;hide&#39;, opacity: &#39;hide&#39;}, &#39;normal&#39;,function(){ $(&#39;#divFloatToolsView&#39;).hide();kf_setCookie(&#39;RightFloatShown&#39;, 1, &#39;&#39;, &#39;/&#39;, &#39;www.istudy.com.cn&#39;); });$(&#39;#aFloatTools_Show&#39;).attr(&#39;style&#39;,&#39;display:block&#39;);$(&#39;#aFloatTools_Hide&#39;).attr(&#39;style&#39;,&#39;display:none&#39;);" href="javascript:void(0);">收缩</a>
				</div>
				<div id="divFloatToolsView" class="floatR" style="display: none">
					<div class="tp"></div>
					<div class="cn">
						<ul>
							<li class="top">
								<h3 class="titZx">QQ咨询</h3>
							</li>
							<li>
								<a class="icoTc" href="http://wpa.qq.com/msgrd?v=3&uin=2073457300&site=qq&menu=yes" target="_blank">客服</a>
							</li>
						</ul>
						<ul>
							<li>
								<h3 class="titDh">电话咨询</h3>
							</li>
							<li>
								<span class="icoTl"></span>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<%= javascript_include_tag "jquery-1.10.2.min" %>
			<%= javascript_include_tag "bootstrap" %>
			<%= javascript_include_tag "jquery.json" %>
			<%= javascript_include_tag "jquery.cookie" %>
			<%= javascript_include_tag "kefu" %>
			<%= javascript_include_tag "my" %>
		</script>
	</body>
	</html>

app/views/carts/show.html.erb
<div class="center">
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<h2>您的购物车</h2>
<table class="table table-bordered table-striped">
  <tr>
    <th>书名</th>
    <th>作者</th>
    <th>出版社</th>
    <th style="text-align:right;">数量</th>
    <th style="text-align:right;">价格</th>
  </tr>
	<% @cart.line_items.each do |item| %>
    <tr class="total_line">
      <td><%= item.book.name %></td>
      <td><%= item.book.author %></td>
      <td><%= item.book.publishing_house %></td>
      <td style="text-align:right;"><%= item.quantity %></td>
      <td class="item_price" style="text-align:right;"><%= item.total_price.to_s + "元" %></td>
    </tr>
  <% end %>
  <tr class="total_line">
    <td colspan="2">总价</td>
    <td colspan="3" class="total_cell" style="text-align:right;">
      <%= @cart.total_price.to_s + "元" %>
    </td> 
	</tr>
</table>
</div>
<br />

<%= link_to "返回继续购书", books_path, class:"btn" %>

<%= link_to "确认订单", new_order_path, class:"btn" %>

<%= button_to '清空购物车', @cart, method: :delete,class:"btn btn-danger pull-right",  confirm: '你确定?' %>