config/routes.rb
Maishu::Application.routes.draw do
  resources :orders do
    get 'search', :on => :collection
    post 'search', :on => :collection
    get 'all', :on => :collection
    post 'all', :on => :collection
  end

  resources :line_items


  resources :carts


  devise_for :users

  get "store/index"

  resources :books do
    post 'import', :on => :collection
    get 'search', :on => :collection
    post 'search', :on => :collection
    get :who_bought, on: :member
  end

  root :to => 'store#index'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	attr_accessible :book_id, :cart_id

	belongs_to :order

	belongs_to :book
	belongs_to :cart


	def total_price
		book.price * quantity
	end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  # before_filter :authenticate_user!
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
    book = Book.find(params[:book_id])
    @line_item = @cart.add_book(book.id, params[:quantity].to_i)
    @line_item.book = book

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart }
        format.json { render json: @line_item,
          status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_id %><br />
    <%= f.number_field :book_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
<tr id="current_item">
	<% else %>
</tr>
<% end %>
<tr>
	<td><%= line_item.quantity %>&times;</td>
	<td><%= line_item.book.name %></td>
	<td class="item_price">
		<%= number_to_currency(line_item.total_price) %>
	</td>
</tr>

app/views/line_items/create.js.erb
// //#START_HIGHLIGHT
// if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }

// //#END_HIGHLIGHT
// $('#cart').html("<%=j render @cart %>");

// $('#current_item').css({'background-color':'#88ff88'}).
//   animate({'background-color':'#114411'}, 1000);

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th>Book</th>
    <th>Cart</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.book_id %></td>
    <td><%= line_item.cart_id %></td>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Book:</b>
  <%= @line_item.book_id %>
</p>

<p>
  <b>Cart:</b>
  <%= @line_item.cart_id %>
</p>


<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>