config/routes.rb
Maishu::Application.routes.draw do
  resources :orders do
    get 'search', :on => :collection
    post 'search', :on => :collection
    get 'all', :on => :collection
    post 'all', :on => :collection
  end

  resources :line_items


  resources :carts


  devise_for :users

  get "store/index"

  resources :books do
    post 'import', :on => :collection
    get 'search', :on => :collection
    post 'search', :on => :collection
    get :who_bought, on: :member
  end

  root :to => 'store#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "1号书店" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <![endif]-->

      <%= stylesheet_link_tag "application", :media => "all" %>

      <!-- For third-generation iPad with high-resolution Retina display: -->
      <!-- Size should be 144 x 144 pixels -->

      <!-- For iPhone with high-resolution Retina display: -->
      <!-- Size should be 114 x 114 pixels -->

      <!-- For first- and second-generation iPad: -->
      <!-- Size should be 72 x 72 pixels -->

      <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
      <!-- Size should be 57 x 57 pixels -->

      <!-- For all other devices -->
      <!-- Size should be 32 x 32 pixels -->

      <%= javascript_include_tag "application" %>
    </head>
    <body>

      <div class="navbar navbar-fixed-top navbar-inverse">
        <div class="navbar-inner">
          <div class="container">
            <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <a class="888" href="/"><%= image_tag("http://levanstaticfile.qiniudn.com/nav_logo.png") %></a>



            <div class="header_center_right">
              <ul class="nav pull-left">
                <li>
                  <%= link_to "书籍", books_path %>
                </li>
                <% if user_signed_in? %>
                <li>
                  <%= link_to "我的订单", search_orders_path %>
                </li>
                <% if current_user.has_role? :admin %>
                <li>
                  <%= link_to "全网订单", all_orders_path %>
                </li>
                <% end %>
                <% end %>

                <li class="divider-vertical"></li>
              </ul>
              <form class="navbar-search" action="/books/search">
                <input class="search-query span3" id="h_search" name="query" type="text" placeholder="ISBN、书名、作者、出版社" >
              </form>
              <ul class="nav pull-right">
                <% if user_signed_in? %>
                <li>
                  <%= link_to current_user.email, edit_user_registration_path %>
                </li>
                <li>
                  <%= link_to "退出", destroy_user_session_path, :method => :delete %>
                </li>
                <% else %>
                <li>
                  <%= link_to "注册", new_user_registration_path %>
                </li>
                <li>
                  <%= link_to "登录", new_user_session_path %>
                </li>
                <% end %>
              </ul></div>
            </div>
          </div>
        </div>
        <div class="center_guide"><a href="index.php" rel="nofollow">查看图书</a></div>
        <div class="container ">
          <div class="row">
            <div class="span10">
              <%= bootstrap_flash %>
              <%= yield %>
            </div>
          </div><!--/row-->

          <footer>
            <p>&copy; 1号书店 2013</p>
          </footer>

        </div> <!-- /container -->

      </body>
      </html>